apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql2-pv-claim
  namespace: default
  labels:
    app: mysql2
spec:
  storageClassName: local-path
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi